config/routes.rb
Rails.application.routes.draw do
  get 'home/about', to: 'root#about'
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'root#top'

  resources :users, only: [ :index, :show, :edit, :update, :destroy]
  resources :books
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :user

  validates :title, presence:true, length: {minimum:1, maximum: 200}
  validates :body, presence:true, length: {minimum:1, maximum: 200}

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  validates :name, presence:true,
                   length: {minimum: 2 ,maximum: 20 }
  validates :introduction, length: {maximum: 50}




  has_many :books

  attachment :profile_image
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

before_action :configure_permitted_parameters, if: :devise_controller?

  def after_sign_in_path_for(resource)
		user_path(current_user.id)
  end

  def after_sign_out_path_for(resource)
  	    flash[:notice] = "successfully"
  	    root_path
  end

  protected
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :email])
    devise_parameter_sanitizer.permit(:sign_in, keys: [:name])
  end
end

Refile.secret_key = '2ada6cbb0944d5ee3a2f04f7164c6bed9c240c45e32eb6b76cd301625bd3144ae805a8495367035d95a4de82d9fde745bcc15b6a6d7a631b037ee8d5a8f8f88e'

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :authenticate_user!
  def index
  	@books = Book.page(params[:page]).reverse_order
    @book=Book.new

  end

  def show
  	@bookj = Book.find(params[:id])
    @book = Book.new
    @user = User.find(@bookj.user.id)
  end

  def new
  	@book = Book.new
  end

  def create
  	@book = Book.new(book_params)
    @book.user_id = current_user.id
    @books = Book.all
  	if @book.save
      flash[:notice]="book was successfully created"
  	  redirect_to book_path(@book)
    else
      render 'index'
    end
  end

  def edit
     @book = Book.find(params[:id])
    if @book.user_id != current_user.id
      redirect_to books_path
    end
  end

  def update
    @book = Book.find(params[:id])

    if @book.update(book_params)
      redirect_to book_path(@book.id),notice:"book was successfully updated"

    else
      flash[:notice]= "error"
      redirect_to book_path(@book.id)
    end
  end

  def destroy
    @book = Book.find(params[:id])
    @book.destroy
    redirect_to books_path
  end

  private
    def book_params
        params.require(:book).permit(:title, :body)
    end

end

app/controllers/root_controller.rb
class RootController < ApplicationController
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!

  def index
    @users = User.all
    @book = Book.new
  end


  def show
  	@user = User.find(params[:id])
    @books = @user.books.page(params[:page]).reverse_order
    @book = Book.new
  end
  def edit
  	@user = User.find(params[:id])
    if @user.id != current_user.id
      redirect_to user_path(current_user.id)
    end
  end
  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
       redirect_to user_path(@user.id),notice:"successfully"
    else
       flash[:notice]= "error"
       redirect_to user_path(@user.id)
    end
  end

  def new
  	@book = Book.new
  end

  def create
  	@book = Book.new(book_params)
  	@book.save
  	redirect_to book_path(@book.id)
  end

private
  def user_params
    params.require(:user).permit(:name, :profile_image, :introduction)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/root_helper.rb
module RootHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/_list.html.erb
<div class="container">
    <div class="row">
        <div class="col-lg-4">
            <h1>User info</h1>
                <div class="profile-container">
                    <%= attachment_image_tag current_user, :profile_image, :fill, 60, 60, format:'jpeg', class:"img-circle pull-left profile-img", fallback: "no_image.jpg" %>
                </div>
                <table class="table">
                        <tbody>
                            <tr>
                                <th>name</th>
                                <th><%= current_user.name %></th>
                            </tr>
                            <tr>
                                <th>introduction </th>
                                <th><%= current_user.introduction %></th>
                            </tr>
                        </tbody>
                    </table>

                <p><%= link_to "", edit_user_path(current_user), class: "col-xs-12 btn btn-default glyphicon glyphicon-wrench" %></p>

            <h1>New book</h1>
<!-- form_for部分 -->
            <%= form_for(book, url: '/books') do |f| %>

                <% if @book.errors.any? %>
                    <div id="error_explanation">
                    <h2><%= pluralize(@book.errors.count, "error") %> prohibited this message from being saved:</h2>

                    <ul>
                        <% @book.errors.full_messages.each do |msg| %>
                                <li><%= msg %></li>
                        <% end %>
                    </ul>
                    </div>
                <% end %>

                <h4>Title</h4>
                <%= f.text_field :title, rows:'',class:"title field" %>

                <h4>Body</h4>
                <%= f.text_area :body, class:"body field" %>

                <%= f.submit 'Create Book', class: "btn btn-primary" %>

            <% end %>

        </div>

app/views/books/_list2.html.erb
<div class="container">
    <div class="row">
        <div class="col-lg-4">
            <h1>User info</h1>
                <div class="profile-container">
                    <%= attachment_image_tag book.user, :profile_image, :fill, 60, 60, format:'jpeg', class:"img-circle pull-left profile-img", fallback: "no_image.jpg" %>
                </div>
                <table class="table">
                        <tbody>
                            <tr>
                                <th>name</th>
                                <th><%= user.name %></th>
                            </tr>
                            <tr>
                                <th>introduction </th>
                                <th><%= user.introduction %></th>
                            </tr>
                        </tbody>
                    </table>

                <p><%= link_to "", edit_user_path(user), class: "col-xs-12 btn btn-default glyphicon glyphicon-wrench" %></p>

            <h1>New book</h1>
<!-- form_for部分 -->
            <%= form_for(book, url: '/books') do |f| %>

                <% if @book.errors.any? %>
                    <div id="error_explanation">
                    <h2><%= pluralize(@book.errors.count, "error") %> prohibited this message from being saved:</h2>

                    <ul>
                        <% @book.errors.full_messages.each do |msg| %>
                                <li><%= msg %></li>
                        <% end %>
                    </ul>
                    </div>
                <% end %>

                <h4>Title</h4>
                <%= f.text_field :title, rows:'',class:"title field" %>

                <h4>Body</h4>
                <%= f.text_area :body, class:"body field" %>

                <%= f.submit 'Create Book', class: "btn btn-primary" %>

            <% end %>

        </div>

app/views/books/edit.html.erb
<div class= "col-md-6 col-md-offset-3">
	<h1>編集画面</h1>
<!-- form_for部分 -->
		<%= form_for(@book) do |f| %>
    		<h4>Title</h4>
    			<%= f.text_field :title, class:"col-xs-12" %>
    		<h4>Body</h4>
    			<%= f.text_area :body, class:"col-xs-12" %>
    		<%= f.submit '保存', class:"btn btn-primary col-xs-12" %>
		<% end %>
</div>

app/views/books/index.html.erb
<%= render 'books/list', book: @book %>

		<div class="col-lg-8">
			<h1>Books</h1>

				 <table class= "table table-striped">
    				<tr>
    					<th colspan="" rowspan="" headers="" scope=""></th>
    					<th colspan="" rowspan="" headers="" scope="">Title</th>
    					<th colspan="" rowspan="" headers="" scope="">Body</th>
    				</tr>

    				<% @books.each do |book| %>

    				<tr>
    					<td colspan="" rowspan="" headers="" scope=""><span><%= attachment_image_tag @user, :profile_image, :fill, 10, 10, format:'jpeg', class:"img-circle pull-left profile-img", fallback: "no_image.jpg" ,size:'40x40' %></span></td>
        				<td colspan="" rowspan="" headers="" scope=""><span><%=link_to book.title, book_path(book.id) %></span></td>
        				<td colspan="" rowspan="" headers="" scope=""><span><%= book.body %></span></td>
    				</tr>

 					<% end %>

 				</table>

		</div>
	</div>
</div>

app/views/books/new.html.erb
<h1>New book</h1>
<!-- form_for部分 -->
<%= form_for(@book, url: '/books') do |f| %>

    <h4>Title</h4>
    <%= f.text_field :title %>
 
    <h4>Body</h4>
    <%= f.text_area :body %>
 
    <%= f.submit 'Create Book' %>
 
<% end %>

app/views/books/show.html.erb
  <%= render 'books/list2', book: @book, user:@user %>

<% if flash[:notice] %>
        <%= flash[:notice] %>
<% end %>


<div class="col-lg-8">
	<h1>Book detail</h1>
	<table class="table">
		<tbody>
			<tr>
				<th><%= attachment_image_tag @user, :profile_image, :fill, 10, 10, format:'jpeg', class:"img-circle pull-left profile-img", fallback: "no_image.jpg", size:'40x40' %><br><%=link_to @user.name, user_path(@user) %></th>
				<th><p><%=@bookj.title%></p></th>
				<td><%= @bookj.body %></td>
				<% if @bookj.user == current_user %>
				    <th><%= link_to "Edit", edit_book_path(@bookj) %></th>
			        <th><%= link_to "Destroy", book_path(@bookj), method: :delete, "data-confirm" => "本当に削除しますか?" %></th>
			    <% end %>
			</tr>
		</tbody>
	</table>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers2</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <header>
    <div id="slidemenu">
    <nav class="nav">
      <span>Bookers
      </span>
    
         <ul class="nav navbar-nav navbar-right" data-hover="dropdown" data-animations="zoomIn fadeIn fadeInUp fadeIn">
         <% if user_signed_in? %>
        <li class="nav">
          <%= link_to ' Home', user_path(current_user.id), class: "glyphicon glyphicon-home" %>
        </li>
        <li class="">
         <%= link_to " Users", users_path, class: "glyphicon glyphicon-user" %>
        </li>
        <li class="">
         <%= link_to " Books", books_path, class: "glyphicon glyphicon-book" %>
        </li>
        <li class="">
          <%= link_to " Logout", destroy_user_session_path, method: :delete, class: "glyphicon glyphicon-log-out"  %>
        </li>

      <% else %>
        <li class="">
          <%= link_to ' Home', root_path, class: "glyphicon glyphicon-home" %>
        </li>
        <li class="">
          <%= link_to ' About', home_about_path, class: "glyphicon glyphicon-link"  %>
        </li>
        <li class="">
         <%= link_to " sign up", new_user_registration_path, class: "glyphicon glyphicon-edit" %>
        </li>
        <li class="">
          <%= link_to " login", new_user_session_path, class: "glyphicon glyphicon-log-in" %>
        </li>
      <% end %>
      </ul>
      </nav>
    </div>
  </header>
  <body>
    <%= yield %>
  </body>
</html>

app/views/root/about.html.erb
<h1>Welcome to Bookers!</h1>
<p>CopyRight Infratop.inc</p>

app/views/root/top.html.erb

<% if flash[:notice] %>
	<%= flash[:notice] %>
<% end %>
<div class="container">
	<div class="top-message col-md-offset-3 col-md-6">
        <h1 class="auto"> welcom to <span class="glyphicon glyphicon-book"><strong>Bookers</strong> !!</span></h1>
        <p class="center">In <span class="glyphicon glyphicon-book"><strong>Bookers</strong></span><br>
             you can share and exchange your opinions,inpressions,and emotions <br>about various books!</p>
        <%= link_to "sign up", new_user_registration_path, class: "btn btn-info col-xs-10 col-xs-offset-1" %>

        <%= link_to "login", new_user_session_path, class: "btn btn-success col-xs-10 col-xs-offset-1" %>
    </div>
</div>

<footer>
	<div class="container">
		<div class="col-xs-3 col-xs-offset-9">
		    <p>CopyLight Infratop.inc</p>
	    </div>
	</div>
</footer>

app/views/users/edit.html.erb
<div class="body-wrap">
  <div id="st-container" class="st-container">
    <div class="st-pusher">
      <div class="st-content">
        <div class="st-content-inner">
          <section class="slice slice-lg sct-color-1">
              <div class="container">
                  <div class="row">
                      <div class="col-md-4 col-md-offset-4">
                          <div class="form-user style-1 rounded has-shadow-1">
                            <div class="form-header text-center">
                                <h2 class="form-header-title">プロフィール編集</h2>
                            </div>
                            <div class="form-body">
                            <%= form_for(@user) do |f| %>
                                <div class="form-group has-icon">
                                  <label class="control-label sr-only" for="inputEmail">Name</label>
                                    <%= f.text_field :name, autofocus: true, class:"form-control", id:"inputEmail", placeholder:"名前"%>
                                  <span class="fa fa-user form-control-icon" aria-hidden="true"></span>
                                </div>

                                <div class="form-group has-icon">
                                    <div class="user-edit-image">
                                      <%= attachment_image_tag @user, :profile_image, :fill, 60, 60, class: "img-circle pull-left profile-thumb", fallback: "no_image.jpg"%>
                                    </div>
                                    <label class="control-label sr-only" for="user_profile_image">ProfileImage</label>
                                    <%= f.attachment_field :profile_image, placeholder: "プロフィール画像", class: "user-edit-form" %>
                                </div>

                                <div class="form-group has-icon">
                                  <label class="control-label sr-only" for="inputEmail">Introduction</label>
                                    <%= f.text_area :introduction, autofocus: true, class:"form-control", id:"inputEmail", placeholder:"Introduction"%>
                                  <span class="fa fa-user form-control-icon" aria-hidden="true"></span>
                                </div>

                                <%= f.submit "変更を保存", class:"btn btn-lg btn-block btn-base-1 mt-20" %>
                                <% end %>
                              <!-- ここにform_forを追加します -->
                            </div>
                          </div>
                      </div>
                  </div>
              </div>
          </section>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/users/index.html.erb
<div class="container">
    <div class="row">
       <%= render 'books/list', book: @book %>

        <div class="col-lg-8">
            <h1>Users</h1>

                 <table class= "table table-striped" >
                    <tr>
                        <th colspan="" rowspan="" headers="" scope="">Image</th>
                        <th colspan="" rowspan="" headers="" scope="">Name</th>
                        <th colspan="" rowspan="" headers="" scope=""></th>
                    </tr>

                    <% @users.each do |user| %>

                    <tr>
                        <td colspan="" rowspan="" headers="" scope=""><span><%= attachment_image_tag @user, :profile_image, :fill, 40, 40, format:'jpeg', class:"img-circle pull-left profile-img", fallback: "no_image.jpg", size:'40x40' %></span></td>
                        <td colspan="" rowspan="" headers="" scope=""><span><%= user.name %></span></td>
                        <td colspan="" rowspan="" headers="" scope=""><span><%= link_to "show", user_path(user.id) %></span></td>
                    </tr>

                    <% end %>

                </table>
        </div>
    </div>
</div>

app/views/users/show.html.erb
<%= render 'books/list2', book: @book, user: @user %>

<% if flash[:notice] %>
	<%= flash[:notice] %>
<% end %>

<div class="col-lg-8">
			<h1>Books</h1>

				 <table class= "table table-striped">
    				<tr>
    					<th colspan="" rowspan="" headers="" scope=""></th>
    					<th colspan="" rowspan="" headers="" scope="">Title</th>
    					<th colspan="" rowspan="" headers="" scope="">Body</th>
    				</tr>


    				<% @books.each do |book| %>

    				<tr>
    					<td colspan="" rowspan="" https://web-camp.online/lesson/curriculums/191/contents/991headers="" scope=""><span><%= attachment_image_tag @user, :profile_image, :fill, 40, 40, format:'jpeg', class:"img-circle pull-left profile-img", fallback: "no_image.jpg", size:'40x40' %></span></td>
        				<td colspan="" rowspan="" headers="" scope=""><span><%=link_to book.title, book_path(book.id) %></span></td>
        				<td colspan="" rowspan="" headers="" scope=""><span><%= book.body %></span></td>
    				</tr>

 					<% end %>

 				</table>
	</div>